### PR TITLE
Adds asm.js support

### PR DESCRIPTION
**Pull request by arcanis**
Here and back again 😃 

This is a followup to https://github.com/atom/text-buffer/issues/183 and https://github.com/atom-archive/buffer-offset-index/pull/2

This PR adds asm.js support to this library through embind (instead of nbind). I've tried to keep changes as minimal as possible in the core. Everything tested is supported.

**Possibly breaking changes:**

- https://github.com/atom/superstring/compare/master...arcanis:master#diff-959292f9667b4cf4919bbae193a31523L57

  (returning sometimes an array and sometimes an object was causing unnecessary complications)

- https://github.com/atom/superstring/compare/master...arcanis:master#diff-e5c4747c80e4a1872cde8e24121784c0L9

  (inheriting instead of typedefing allows me to write more stable template overloads)

- https://github.com/atom/superstring/compare/master...arcanis:master#diff-ae762b481da801d5c00c8c9e5890f6e9L148

  (Buffer aren't supported under browser environments)

... and of course the `delete()` method (which has been polyfilled as a noop inside the v8 bindings).

All the tests are currently passing, ~~except for `Patch.compose` that I have not yet been able to implement. Even if it is technically supported, the embind library has safety checks that cannot be disabled (but should, cf https://github.com/kripken/emscripten/issues/4863) that make it hard to support vectors of objects~~.

WDYT?

### CODE REVIEW

**Comment by arcanis** [comment]
Note that the failing test is also failing in master. You may have fixed it already in #5.

**Comment by arcanis** [comment]
I went ahead and implemented `Patch.compose` by hijacking the embind cast ([here](https://github.com/atom/superstring/pull/7/files#diff-5250a5a28e24ded85a19f944193677a2R1)). It's not great, but it's not that bad either, the required change being very small (just a type that needed to be wrapped inside `AllowedRawPointer<T>` when working with pointers). Plus, it hopefully won't break even after the fix lands in the emscripten.

Since it was the last thing remaining, I think that this PR should be ready to merge :)

**Comment by arcanis** [comment]
I reverted snakecase bindings on `BufferOffsetIndex`, which I believe were unintentional and were breaking the text-buffer package.

**Comment by maxbrunsfeld** [comment]
@arcanis This is really cool. We have a few questions for you:

1. Can you explain what your `WRAP` macros are doing? From the [embind docs](https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/embind.html#classes), it looks like you can just pass a pointer to a non-static member function directly to embind's `.function` method. Is there something about our methods that requires additional wrapping?

2. Are there any ways that we could change our core APIs to make the asm.js wrapping code simpler?

3. After having done this work, what are your thoughts on using `embind` vs `nbind`? Are you happy with the way this ended up, as compared to your earlier PR? Do you think we were wrong to suggest `embind`; would it have been better to create the asm.js bindings using `nbind` and continue to use the v8 API directly for the node bindings?

4. Regarding your fix for unaligned reads in Patch deserialization, do you think it would be better to ensure that all 32-bit values are written to aligned addresses during serialization, so that we could perform 32-bit reads during deserialization? I'm not sure if there would be a noticeable performance difference.

Overall, we really want this feature, but the template meta-programming in `autowrap.h` is pretty challenging for us to understand, with our current C++ skill level. I think we can probably maintain it if necessary, but if there's anything we can do to simplify the wrapping code, it would make our jobs easier. Thanks so much!

**Comment by arcanis** [comment]
- The `em_wrap_type` template associates a "local type" (the type that is used on the C++ side) with a "wire type" (the type that is used on the JS side). Its `receive` method takes a Wire Type and use it to build a Local Type, and the `transmit` method do the exact opposite, taking a Local Type and 'serializing' it into a Wire Type (for example, vectors are serialized into JS arrays). There's a template specialization for each significant type, and more specializations might be added in the future (for example, if you decide to use `std::set` in the future, a new entry will be added).

  The `em_wrap_fn` template takes a member function as parameter, and automatically apply the `em_wrap_type<>::receive` method on each parameter, and the `em_wrap_type<>::transmit` method on the returned value. Basically, it unserialize each argument and return a serialized value to the JS side. Those templates shouldn't have to be modified, their implementation is complete.

  The `WRAP` macros are just shorthands to call the templates without specifying redundant informations (for example, the `em_wrap_fn` template requires the function pointer but also its type, which can be deduced with the `decltype` keyword).

  This micro-framework is useful to support every type that isn't natively supported by embind. For example, the `flat_set` type needs to be casted to a javascript `Set`, but that obviously isn't supported by embind. Same for `std::vector`, `std::unordered_map`, etc.

  - Not really. The embind library does a lot of magic for sure, but some is missing (sometimes because embind cannot make assumptions about the userland code) and has to be implemented on the wrapper itself.

  - Hm, they're really different. After my initial PR I went on and used nbind to port https://github.com/facebook/yoga, and it worked pretty well. However, there's still a couple issues that are still problematic (but the maintainer is usually really quick at fixing them, which is great). All things considered, I think that nbind is the right move *generally speaking* (a larger community should support it, test it, improve it), but if you already have V8 bindings then maybe embind is the easiest way to add new ones. The API is full C++ and doesn't use macros, which make it a bit easier to figure out how to hack the engine like I do with auto-wrap & co.

  - Not really. The issue isn't so much that data aren't aligned in the buffer, but rather that the buffer isn't aligned on 4 bytes. Since we're allocating a `std::vector<uint8_t>`, then the allocated buffer will not have alignment informations. I've tried allocating a `std::vector<uint8_t __attribute__((aligned(4)))>` instead, but it seems that the alignment attribute isn't used by the standard container allocators. I've read some docs, and it seems to be a problem in the C++ standard, and both Clang and GCC are affected.

  - I can see the issue with the metaprogramming. The whole idea behind it is that it makes it quite easy to register new types (about ten lines), and that once implemented a binding can be used for each function, being more DRY and avoiding possible mistakes. Unfortunately, it comes with a cost, and this cost is clarity. That being said, I would be happy to review any changes you would like to make to this micro-framework if that can help you.

**Comment by nathansobo** [comment]
Hey @arcanis. Good answers. @maxbrunsfeld and myself both have overlapping vacations until the end of next week. When we return we will investigate this a bit more and proceed. Just wanted to let you know this could sit for a few days but we haven't forgotten about it.

**Comment by arcanis** [comment]
No worry, thanks for the heads-up :)

**Comment by arcanis** [comment]
@nathansobo Have you had the chance to review this?

**Comment by nathansobo** [comment]
We've gotten pulled off to more reactive topics. I'll talk to @maxbrunsfeld about it this week.

**Comment by nathansobo** [comment]
Hey @arcanis. As you can see we're pushing some adjustments to your branch. We plan to drop reliance on the legacy `Patch` change fields in `text-buffer` and then merge. Thanks for your patience.

**Comment by maxbrunsfeld** [comment]
Thanks so much for figuring this all out, @arcanis. I'll publish a new version of this module shortly and make the necessary changes in `text-buffer` to use the new version.

**Comment by nathansobo** [comment]
❤️  Thanks for the contribution.

**Pull request merged**
