### PR TITLE
Add CodeQL Analysis workflow

### PR DESCRIPTION
**Pull request by jhutchings1**
Adds a GitHub Actions workflow that runs CodeQL on every push, and on a daily schedule.

Code scanning looks for vulnerabilities, such as XSS, SQL injection, etc., in your code. If it finds any new vulnerabilities it surfaces them in the PR as check annotations, and blocks the build until they’re fixed or marked as false positives. If it finds any on the repo’s default branch it displays them in the [security tab](../security/code-scanning).

For now you also need to be feature flagged to see results in the security tab (as well as having write permission on this repo) - if you drop an email to jhutchings1@github.com I can get anyone you need added. 

Finally, this is an early access program, so please don't share screenshots/tweet about this before May 6th when we're unveiling it at GitHub Satellite. 

Cc: @greysteil

### CODE REVIEW

**Comment by jhutchings1** [comment]
This analysis is all working in the fork, so you should be good to merge any time.

**Comment by maxbrunsfeld** [comment]
🎉

**Comment by maxbrunsfeld** [comment]
How do you view the results of the analysis? Should the action have an artifact uploaded that contains the results? I see lines like this in the logs:

```
  [25/25] Evaluation done (1.2s); writing results to codeql-cpp/Likely Bugs/Conversion/CastArrayPointerArithmetic.bqrs.
```

but there is no artifact uploaded.

**Comment by greysteil** [comment]
Any findings will show up in the Security tab on the repo, under code scanning (if there's no tab showing for you it may be because we haven't flipped a feature flag for you  - let me know). They'll also show up as check annotations on the commit.

**Comment by lkashef** [comment]
@jhutchings1 @maxbrunsfeld this job has been failing for a while

I just wanted to make sure it's on your radar, any help required on my end, just let me know.

https://circleci.com/gh/atom/superstring/310?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by maxbrunsfeld** [comment]
Hmm, I think that is just a spurious failure on Circle. This PR just adds a GitHub Actions config file, so I don't think it should affect the Circle CI run. Maybe I'm missing something though?

**Comment by lkashef** [comment]
@maxbrunsfeld,  Sorry about that, yeah it looks like CircleCI depreciated the x-code version 8.3.3, and we have to upgrade to one of the [supported versions](https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions).

If you want me to jump on that, let me know.

_FYI, you need to authenticate with github to gain access, I see that you are on the members list._

**Pull request merged**
